DROP TABLE soferi;
DROP TABLE clienti;
DROP TABLE curse;
DROP TABLE depou;
DROP TABLE vehicule_depou;
DROP TABLE 
/

create TABLE soferi(
NUME	VARCHAR2(50 BYTE),
PRENUME	VARCHAR2(20 BYTE),
NR_TELEFON	NUMBER(10,0),
ID	INT NOT NULL PRIMARY KEY ,
CNP	NUMBER(10,0)
);
/
create table clienti(
NUME	VARCHAR2(50 BYTE),
PRENUME	VARCHAR2(20 BYTE)

);
/
CREATE TABLE curse(
  ID INT  NOT NULL PRIMARY KEY
);
/
CREATE TABLE depou(
ADRESA varchar2(50) NOT NULL,
ID_D INT NOT NULL PRIMARY KEY ,
CAPACITATE INT NOT NULL
);

/

CREATE TABLE vehicule_depou(
ID_V INT NOT NULL PRIMARY KEY ,
CAPACITATE_PASAGERI INT NOT NULL,
STARE INT NOT NULL       
);

